MD025:
  front_matter_title: ""
  level: 1
MD033:
  allowed_elements: ["pre","script","style","code","a","img","link","HoverNote","iframe","ECharts"]
MD013:
  line_length: 250
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: false
  tables: true
  headings: true
  strict: false
  stern: false
# 在ansi代码块中使用$符号
MD014: false
MD046:
  style: fenced